### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by antic-eye** [jonsterling/Tasky#2]
Hi,

I wanted to give Tasky a try but I was not able to start it.

After `git clone` I had to install the package `python-urwid`. When I try to start tasky I receive the error:

```
foo@bar:/opt/tasky$ ./tasky.py
Traceback (most recent call last):
  File "./tasky.py", line 158, in <module>
    Tasky()
  File "./tasky.py", line 36, in __init__
    self.refresh()
  File "./tasky.py", line 52, in refresh
    self.walker[:] = map(TaskWidget, self.warrior.pending_tasks(limit))
  File "/opt/tasky/taskwidget.py", line 8, in __init__
    desc = urwid.Text(task.description())
  File "/opt/tasky/taskwarrior.py", line 18, in description
    return self.data.get('description', '')
AttributeError: 'list' object has no attribute 'get'
```

Any ideas what might fail?

System is Ubuntu jessie/sid:

```
Linux capillatus 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Other infos:

```
task --version
2.5.0
```

```
python --version
Python 2.7.6
```

Thank you :)

**Comment by mutantcornholio** [comment]
I get same one

**Comment by Trial-In-Error** [comment]
Same!

**Comment by jonsterling** [comment]
Thank you all!! I've merged the PR :smile:
